MPS-23860 behavior throws NoSuchMethodError since the editor creates instances of abstract concepts.
No fix has been introduced, only a warning on every child link