Checking fot isDisposed flag within the editor, fixing:
java.lang.IllegalStateException: Disposed events collector was called: class jetbrains.mps.nodeEditor.updater.UpdaterModelListener
	at jetbrains.mps.smodel.ModelsEventsCollector.checkNotDisposed(ModelsEventsCollector.java:109)
	at jetbrains.mps.smodel.ModelsEventsCollector.clearCollectedEvents(ModelsEventsCollector.java:90)
	at jetbrains.mps.nodeEditor.updater.UpdaterModelListener.clearCollectedEvents(UpdaterModelListener.java:53)
	at jetbrains.mps.nodeEditor.updater.UpdaterModelListenersController.clearCollectedEvents(UpdaterModelListenersController.java:147)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.update(UpdaterImpl.java:82)
	at jetbrains.mps.nodeEditor.EditorComponent.rebuildEditorContent(EditorComponent.java:1773)
	at jetbrains.mps.nodeEditor.NodeEditorComponent.rebuildEditorContent(NodeEditorComponent.java:112)
	at jetbrains.mps.nodeEditor.EditorComponent$3$1.run(EditorComponent.java:279)