Temporarily correcting java.lang.NoClassDefFoundError: jetbrains/mps/tool/builder/MpsWorker caused by apache logging loading resources using through Thread.contextClassLoader & problem with looping within MPS class loaders.