fix tests fail
extract MPSProject out from executing under writeAction in IdeaEnviroment.doDispose() to prevent:
java.lang.RuntimeException: java.lang.IllegalStateException: Must not call closeProject() from under write action because fireProjectClosing() listeners must have a chance to do something useful
PS removing writeAction here will lead to 'java.lang.AssertionError: Assertion failed: Write access is allowed inside write-action only' from IdeaTestApplication.java:68