MPS-22296 Java Command does not load openapi classes at all: in the distribution JDK stub module consider mps-openapi.jar as its classes_gen folder. When the java class path for a new process is calculated the whole JDK classpath is dropped (because nobody needs classes.jar and tools.jar on the new jvm). Unfortunately mps-opeanpi.jar is dropped as well, and that leads to NoClassDefFoundErrors for the openapi java classes.